config/routes.rb
Rails.application.routes.draw do
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  root "palettes#index"

  resources :palettes
  resources :users, only: %i[] do
    get :sign_in, on: :collection
    post :session, to: "users#create_session", on: :collection
    delete :sign_out, on: :collection
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :user
end

app/models/palette.rb
class Palette < ApplicationRecord
  belongs_to :user

  serialize :colors, coder: JSON, type: Array, default: []

  validates :name, presence: true, uniqueness: true
  validates :colors, presence: true, length: { is: 5 }, uniqueness: true

  after_initialize :set_colors

  private

  def set_colors
    self.colors = Array.new(5) { '#' + SecureRandom.hex(3) } unless self.colors.present?
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates :username, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  def current_user
    Current.user ||= session[:user_id] && User.find_by(id: session[:user_id])
  end
  helper_method :current_user

  def login(user)
    reset_session
    session[:user_id] = user.id
    Current.user = user
  end

  def logout
    reset_session
    Current.user = nil
  end
end

app/controllers/palettes_controller.rb
class PalettesController < ApplicationController
  before_action :set_palette, only: %i[ show edit update destroy ]
  before_action :authorize_owner, only: %i[ edit update destroy ]

  # GET /palettes
  def index
    @palettes = Palette.eager_load(:user).all
  end

  # GET /palettes/1
  def show
  end

  # GET /palettes/new
  def new
    @palette = Palette.new
  end

  # GET /palettes/1/edit
  def edit
  end

  # POST /palettes
  def create
    @palette = Palette.new(palette_params.merge(user: current_user))

    if @palette.save
      redirect_to @palette, notice: "Palette was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /palettes/1
  def update
    if @palette.update(palette_params)
      redirect_to @palette, notice: "Palette was successfully updated.", status: :see_other
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /palettes/1
  def destroy
    @palette.destroy!
    redirect_to palettes_url, notice: "Palette was successfully destroyed.", status: :see_other
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_palette
      @palette = Palette.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def palette_params
      params.require(:palette).permit(:name).merge({colors: params[:palette][:colors]&.split(" ") || [] })
    end

    def authorize_owner
      redirect_to root_path, alert: "You are not authorized to perform this action" unless @palette.user == current_user
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def sign_in
  end

  def create_session
    user = User.find_by(username: params[:user][:username])
    if user&.authenticate(params[:user][:password])
      login(user)
      redirect_to root_path, notice: "Logged in successfully"
    else
      redirect_to sign_in_users_path, alert: "Invalid email or password"
    end
  end

  def sign_out
    logout
    redirect_to root_path, notice: "Logged out successfully"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/palettes_helper.rb
module PalettesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Excel-lent palettes: Color Schemes from Your Nightmares</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>

    <meta name="turbo-refresh-method" content="morph">
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
  </head>

  <body>

  <header class="p-5 text-center border-b-4 border-green-300">
    <a href="/" class="text-4xl font-bold underline decoration-pink-500 decoration-wavy underline-offset-8 mb-2" style="font-family: 'Press Start 2P', cursive;">
      Excel-lent Palettes
    </a>
    <p class="text-lg font-light italic text-amber-500 animate-[header-animation_1s_infinite]">
      Color Schemes from Your Nightmares
    </p>

    <div class="flex justify-center space-x-4 mt-3">
      <% if current_user.present? %>
        <%= link_to "New Palette", new_palette_path, class: "bg-blue-500 hover:bg-blue-600 text-white font-bold py-2 px-4 rounded shadow transform rotate-3 rainbow-hover" %>
        <%= button_to "Sign Out", sign_out_users_path, method: "delete", class: "bg-red-500 hover:bg-red-600 text-white font-bold py-2 px-4 rounded shadow transform -rotate-6 glitch" %>
      <% else %>
        <%= link_to "Sign In", sign_in_users_path, class: "bg-green-500 hover:bg-green-600 text-white font-bold py-2 px-4 rounded shadow transform -rotate-9 glitch" %>
      <% end %>
    </div>
    </header>

    <main class="container mx-auto mt-5 px-5 flex">
      <%= yield %>
    </main>
  </body>
</html>

app/views/palettes/_demo.html.erb
<%-
  data = [{
            name: "Employee Time Allocation",
            row: 6,
            column: 6,
            config: { columnlen: { "0": 105, "1": 145, "2": 135, "3": 175, "4": 175 } },
            celldata: [
              { r: 0, c: 0, v: { m: "Employee Name", bg: palette.colors[0], it: 1, un: 1, bl: 1, tb: 2 } },
              { r: 0, c: 1, v: { m: "Time Spent in Meetings", bg: palette.colors[0], it: 1, un: 1, bl: 1, tb: 2 } },
              { r: 0, c: 2, v: { m: "Time Spent on Emails", bg: palette.colors[0], it: 1, un: 1, bl: 1, tb: 2 } },
              { r: 0, c: 3, v: { m: "Time Spent on Actual Work", bg: palette.colors[0], it: 1, un: 1, bl: 1, tb: 2 } },
              { r: 0, c: 4, v: { m: "Time Spent on Coffee Breaks", bg: palette.colors[0], it: 1, un: 1, bl: 1, tb: 2 } },
              { r: 1, c: 0, v: { m: "John Doe", fc: palette.colors[1], it: 1 } },
              { r: 1, c: 1, v: { m: "25 hrs/week", bg: palette.colors[1] } },
              { r: 1, c: 2, v: { m: "10 hrs/week", bg: palette.colors[2] } },
              { r: 1, c: 3, v: { m: "5 hrs/week", bg: palette.colors[2] } },
              { r: 1, c: 4, v: { m: "8 hrs/week", bg: palette.colors[4] } },
              { r: 2, c: 0, v: { m: "Jane Smith", fc: palette.colors[1], it: 1 } },
              { r: 2, c: 1, v: { m: "20 hrs/week", bg: palette.colors[2] } },
              { r: 2, c: 2, v: { m: "15 hrs/week", bg: palette.colors[1] } },
              { r: 2, c: 3, v: { m: "3 hrs/week", bg: palette.colors[1] } },
              { r: 2, c: 4, v: { m: "10 hrs/week", bg: palette.colors[4] } },
              { r: 3, c: 0, v: { m: "Bob Johnson", fc: palette.colors[1], it: 1 } },
              { r: 3, c: 1, v: { m: "30 hrs/week", bg: palette.colors[3] } },
              { r: 3, c: 2, v: { m: "5 hrs/week", bg: palette.colors[3] } },
              { r: 3, c: 3, v: { m: "2 hrs/week", bg: palette.colors[3] } },
              { r: 3, c: 4, v: { m: "6 hrs/week", bg: palette.colors[4] } },
              { r: 4, c: 0, v: { m: "Sally Johnson", fc: palette.colors[1], it: 1 } },
              { r: 4, c: 1, v: { m: "10 hrs/week", bg: palette.colors[4] } },
              { r: 4, c: 2, v: { m: "20 hrs/week", bg: palette.colors[4] } },
              { r: 4, c: 3, v: { m: "10 hrs/week", bg: palette.colors[4] } },
              { r: 4, c: 4, v: { m: "5 hrs/week", bg: palette.colors[4] } },
            ]
          }]
%>

<%= turbo_mount("Workbook", props: {data:}, class: "w-full max-w-full overflow-hidden h-64 relative") %>

app/views/palettes/_form.html.erb
<%= form_with(model: palette, class: "contents bg-gradient-to-br from-yellow-200 via-pink-500 to-purple-400 p-5 border-4 border-dotted border-black") do |form| %>
  <% if palette.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2 style="font-family: 'Comic Sans MS', cursive, sans-serif; color: blue;"><%= pluralize(palette.errors.count, "error") %>
        prohibited this palette from being saved:</h2>

      <ul>
        <% palette.errors.each do |error| %>
          <li style="color: green;"><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name, style: "font-family: 'Comic Sans MS', cursive, sans-serif; color: magenta;" %>
    <%= form.text_field :name, class: "block shadow appearance-none border rounded-md border-red-500 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :colors, style: "font-family: 'Comic Sans MS', cursive, sans-serif; color: orange;" %>

    <%= turbo_mount("ColorPicker", props: { colors: palette.colors }) do |controller_name| %>
      <div data-<%= controller_name %>-target="mount"></div>
      <%= form.hidden_field :colors, data: { "#{controller_name}-target": "input" } %>
    <% end %>
  </div>

  <div class="inline">
    <%= form.submit "Save Palette", class: "rounded-lg py-3 px-5 bg-green-500 hover:bg-green-700 text-white inline-block font-medium cursor-pointer", style: "border: 2px dashed yellow; font-family: 'Comic Sans MS', cursive, sans-serif;" %>
  </div>
<% end %>

app/views/palettes/_palette.html.erb
<div id="<%= dom_id palette %>" class="w-48">
  <div class="mb-5 block rounded-xl overflow-hidden relative shadow-xl border-4 border-dotted border-pink-600 bg-yellow-100">
    <% palette.colors.each_with_index do |color, i| %>
      <div
        style="background-color: <%= color %>; animation: pulse 10s infinite alternate;"
        class="w-48 <%= i.zero? ? "h-16" : "h-8" %> block"
      >
        <div class="opacity-0 hover:opacity-100 relative w-full h-full transition duration-300 ease-in-out">
          <div class="text-xs absolute bottom-0 left-0 bg-gray-700/75 text-white p-1 rounded-tr">
            <%= color %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
  <p class="bg-pink-200 p-2">
    <span class="text-xs text-white float-right">
      by @<%= palette.user.username %>
    </span>
    <%= link_to(palette.name, palette, class:"block font-medium text-lg text-red-700 underline") %>
  </p>
</div>

app/views/palettes/edit.html.erb
<div class="mx-auto md:w-2/3 w-full p-5 border-4 border-dotted border-black">
  <h1 class="font-bold text-4xl text-red-600" style="text-shadow: 2px 2px 2px #0000FF;">Editing palette</h1>

  <%= render "form", palette: @palette %>

  <%= link_to "Show this palette", @palette, class: "ml-2 rounded-lg py-3 px-5 bg-blue-400 inline-block font-medium text-white hover:bg-blue-600 hover:text-yellow-300", style: "border: 3px dashed red; font-family: 'Comic Sans MS', cursive, sans-serif;" %>
  <%= link_to "Back to palettes", palettes_path, class: "ml-2 rounded-lg py-3 px-5 bg-purple-500 inline-block font-medium text-white hover:bg-purple-700 hover:text-yellow-300", style: "border: 3px dashed yellow; font-family: 'Comic Sans MS', cursive, sans-serif;" %>
</div>

app/views/palettes/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-lime-200 mb-5 text-pink-700 font-comic-sans text-xl border-4 border border-pink-700 text-center" id="notice"><%= notice %></p>
  <% end %>

  <div id="palettes" class="my-8 min-w-full gap-8 flex flex-wrap">
    <%= render @palettes %>
  </div>
</div>

app/views/palettes/new.html.erb
<div class="mx-auto md:w-2/3 w-full p-5 border-4 border-dotted border-black">
  <h1 class="font-bold text-4xl text-red-600" style="text-shadow: 2px 2px 2px #0000FF;">New palette</h1>

  <%= render "form", palette: @palette %>

  <%= link_to "Back to palettes", palettes_path, class: "ml-2 rounded-lg py-3 px-5 bg-purple-500 inline-block font-medium text-white hover:bg-purple-700 hover:text-yellow-300", style: "border: 3px dashed yellow; font-family: 'Comic Sans MS', cursive, sans-serif;" %>
</div>

app/views/palettes/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="w-full flex flex-col gap-4">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-lime-200 mb-5 text-pink-700 font-comic-sans text-xl border-4 border border-pink-700 text-center" id="notice"><%= notice %></p>
    <% end %>

    <nav class="text-sm font-medium text-purple-500 mb-5" style="font-family: 'Comic Sans MS', cursive, sans-serif;">
      <a href="<%= palettes_path %>" class="hover:text-purple-800">Palettes</a> &gt;
      <span class="text-yellow-300"><%= @palette.name %></span>
    </nav>


    <%= turbo_mount("HelloReact", props: {name: 'Mounted React'}) %>
    <%= turbo_mount("HelloSvelte", props: {name: 'Mounted Svelte'}) %>
    <%= turbo_mount("HelloVue", props: {name: 'Mounted Vue'}) %>

    <div class="flex gap-8 justify-center">
      <%= render @palette %>

      <div class="flex flex-col gap-4">
        <% if @palette.user == current_user %>
          <%= link_to "Edit this palette", edit_palette_path(@palette), class: "rounded-lg py-3 px-5 bg-blue-400 inline-block font-medium text-white hover:bg-blue-600 hover:text-yellow-300", style: "border: 3px dashed red; font-family: 'Comic Sans MS', cursive, sans-serif;" %>
          <%= button_to "Destroy this palette", @palette, method: :delete, class: "rounded-lg py-3 px-5 bg-red-500 inline-block font-medium text-white hover:bg-red-700 hover:text-green-300", style: "border: 3px dashed yellow; font-family: 'Comic Sans MS', cursive, sans-serif;" %>
        <% end %>
      </div>
    </div>

    <h2 class="text-2xl font-semibold text-red-500 mt-5 mb-2" style="font-family: 'Comic Sans MS', cursive, sans-serif;">Demo:</h2>
    <%= render partial: "demo", locals: { palette: @palette } %>
  </div>
</div>

app/views/users/sign_in.html.erb
<div class="mx-auto md:w-1/3 w-full">
  <h1 class="font-bold text-4xl text-green-400" style="text-shadow: 2px 2px 2px #ff0000;">Sign in</h1>
  <div class="bg-gradient-to-br from-yellow-200 via-pink-500 to-purple-400 shadow-xl rounded px-8 pt-6 pb-8 mb-4 mt-4">
    <%= form_for :user, url: session_users_path do |f| %>
      <% if flash[:alert] %>
        <div class="bg-yellow-100 border border-orange-500 text-orange-700 px-4 py-3 rounded relative" role="alert">
          <strong class="font-bold">Oopsie!</strong>
          <span class="block sm:inline"><%= flash[:alert] %></span>
          <marquee>🚨🚨🚨</marquee>
        </div>
      <% end %>
      <div class="mb-4">
        <%= f.label :username, class: "block text-indigo-800 text-sm font-bold mb-2" %>
        <%= f.text_field :username, value: "user", class: "shadow appearance-none border rounded w-full py-2 px-3 text-purple-700 leading-tight focus:outline-none focus:shadow-outline" %>
      </div>
      <div class="mb-6">
        <%= f.label :password, class: "block text-indigo-800 text-sm font-bold mb-2" %>
        <%= f.password_field :password, value: "qwerty", class: "shadow appearance-none border border-red-500 rounded w-full py-2 px-3 text-purple-700 mb-3 leading-tight focus:outline-none focus:shadow-outline" %>
      </div>
      <div class="flex items-center justify-between">
        <%= f.submit "Log Me In!", class: "bg-red-500 hover:bg-red-700 text-white cursor-pointer font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" %>
      </div>
    <% end %>
  </div>
</div>